/**
 * Per-customer AI Agent Sandbox simulations.
 *
 * Each customer gets an *isolated* simulation (sandbox/sandbox.md): synthetic
 * inputs run through the full agent flow —
 *
 *   Context Builder → Investigation Orchestrator → Scenario Generator +
 *   Deterministic tools → Scenario Simulator & Match Scorer → Evidence Critic →
 *   Decision-Evidence Agent → Report Writer
 *
 * The data is mock, but it is shaped like a real run: every Gemma stage lists
 * its compact input / structured output, every deterministic stage lists the
 * registered tool calls it made, and the anomaly breakdown exposes the actual
 * math so a reviewer can see *why this transaction matters, why a scenario
 * fails, and why the case is marked as risk*.
 */

import { Sandbox } from './types';

/** CASE-1001 — Nusantara Textiles (the "Best Demo Story", architecture §36). */
const SANDBOX_1001: Sandbox = {
  runId: 'SBX-1001-a7f3',
  model: 'gemma-3-4b-it',
  runtime: 'llama.cpp · Q4_K_M · localhost',
  boundaryHeld: true,
  seed: 100234,
  totalDurationMs: 4820,
  anomaly: {
    score: 89,
    deviationLevel: 'Severe',
    matters:
      '₹12L landed from a first-seen international sender, and ₹9.5L left to five brand-new accounts within 40 minutes — 26× this customer’s typical ₹45K flow.',
    markedRisk:
      'Four independent personalized signals fired at once (amount, velocity, beneficiary novelty, geography). Any one is explainable; together they match a layering footprint, so the case is held for human review — not cleared automatically.',
    signals: [
      {
        key: 'amount_z',
        label: 'Amount deviation',
        metric: 'z-score',
        value: '6.4σ',
        contribution: 28,
        fired: true,
        why: '₹12,00,000 sits far beyond this customer’s trusted range [₹10K–₹1.5L]. z = (1200000 − 45000) / σ ≈ 6.4, well past the 3σ review threshold.',
      },
      {
        key: 'velocity',
        label: 'Transaction velocity',
        metric: 'count / hr',
        value: '17 vs 4',
        contribution: 22,
        fired: true,
        why: '17 transactions in the trigger hour against a normal max of 4/hr. Rapid outflow of freshly-received funds is the defining signal of layering.',
      },
      {
        key: 'benef_novelty',
        label: 'Beneficiary novelty',
        metric: 'new / total',
        value: '5 new',
        contribution: 24,
        fired: true,
        why: 'Known-beneficiary ratio dropped from 0.92 to 0.41 in one hour. Five first-seen accounts received funds simultaneously.',
      },
      {
        key: 'geo_novelty',
        label: 'Geographic novelty',
        metric: 'p(country)',
        value: 'UAE inbound',
        contribution: 15,
        fired: true,
        why: 'International inbound frequency for this twin is 0.03. A first foreign credit of this size is a >30× novelty.',
      },
      {
        key: 'time',
        label: 'Active hours',
        metric: 'in-window',
        value: '10:02',
        contribution: 0,
        fired: false,
        why: 'Trigger time falls inside the usual 08:00–21:00 window, so timing adds no risk. Shown to prove the model does not over-flag.',
      },
    ],
  },
  flow: {
    nodes: [
      { id: 'src', label: 'Intl. Sender', kind: 'SOURCE', amount: '₹12.0L', verified: 'UNKNOWN' },
      { id: 'cust', label: 'Nusantara', kind: 'CUSTOMER' },
      { id: 'b1', label: 'Supplier A', kind: 'BENEFICIARY', amount: '₹2.1L', verified: 'VERIFIED' },
      { id: 'b2', label: 'Supplier B', kind: 'BENEFICIARY', amount: '₹2.0L', verified: 'VERIFIED' },
      { id: 'b3', label: 'Supplier C', kind: 'BENEFICIARY', amount: '₹1.9L', verified: 'VERIFIED' },
      { id: 'b4', label: 'Supplier D', kind: 'BENEFICIARY', amount: '₹1.8L', verified: 'UNKNOWN' },
      { id: 'b5', label: 'Entity E', kind: 'BENEFICIARY', amount: '₹1.7L', verified: 'FLAGGED' },
    ],
    edges: [
      { from: 'src', to: 'cust', amount: '₹12.0L' },
      { from: 'cust', to: 'b1', amount: '₹2.1L' },
      { from: 'cust', to: 'b2', amount: '₹2.0L' },
      { from: 'cust', to: 'b3', amount: '₹1.9L' },
      { from: 'cust', to: 'b4', amount: '₹1.8L' },
      { from: 'cust', to: 'b5', amount: '₹1.7L' },
    ],
  },
  transactions: [
    {
      id: 'TXN-100201',
      label: 'Domestic supplier payment',
      amount: '₹38,000',
      timestamp: '2026-07-15 11:20',
      direction: 'OUT',
      risky: false,
      riskScore: 6,
      reason: 'Within trusted range',
      explanation:
        'A routine ₹38,000 payment to a known supplier — well inside the ₹10K–₹1.5L trusted range and consistent with the usual textile-retail cash cycle.',
      firedSignals: [],
    },
    {
      id: 'TXN-100219',
      label: 'Customer receipt',
      amount: '₹52,000',
      timestamp: '2026-07-16 14:05',
      direction: 'IN',
      risky: false,
      riskScore: 4,
      reason: 'Known counterparty',
      explanation:
        'Inbound receipt from a long-standing domestic buyer. Amount, timing, and channel all match this customer’s established twin.',
      firedSignals: [],
    },
    {
      id: 'TXN-100234',
      label: 'Intl. sender credit',
      amount: '₹12,00,000',
      timestamp: '2026-07-18 10:02',
      direction: 'IN',
      risky: true,
      riskScore: 89,
      reason: 'Amount + geography deviation',
      explanation:
        '₹12,00,000 from a first-seen international sender is 26× the customer’s typical amount and the first-ever foreign inbound credit. This is the trigger transaction for CASE-1001.',
      firedSignals: ['Amount deviation', 'Geographic novelty'],
    },
    {
      id: 'TXN-100235',
      label: 'Transfer to Supplier A',
      amount: '₹2,10,000',
      timestamp: '2026-07-18 10:14',
      direction: 'OUT',
      risky: true,
      riskScore: 61,
      reason: 'Part of rapid redistribution',
      explanation:
        'Outbound leg of the 40-minute redistribution. Supplier A is independently verified, which weakens — but does not clear — the layering hypothesis for this leg.',
      firedSignals: ['Transaction velocity'],
    },
    {
      id: 'TXN-100236',
      label: 'Transfer to Supplier D',
      amount: '₹1,80,000',
      timestamp: '2026-07-18 10:27',
      direction: 'OUT',
      risky: true,
      riskScore: 74,
      reason: 'New beneficiary, unverified',
      explanation:
        'Supplier D is a first-seen beneficiary with no verification on file. Combined with the velocity of the redistribution, this leg carries meaningfully higher risk than the verified suppliers.',
      firedSignals: ['Beneficiary novelty', 'Transaction velocity'],
    },
    {
      id: 'TXN-100237',
      label: 'Transfer to Entity E',
      amount: '₹1,70,000',
      timestamp: '2026-07-18 10:41',
      direction: 'OUT',
      risky: true,
      riskScore: 88,
      reason: 'Flagged beneficiary',
      explanation:
        'Entity E was flagged during screening — no verifiable business registration was found. This is the single highest-risk leg of the redistribution and the strongest evidence for the layering scenario.',
      firedSignals: ['Beneficiary novelty', 'Transaction velocity', 'Geographic novelty'],
    },
  ],
  branches: [
    { id: 'n1', transactionId: 'TXN-100201', x: 0.18, y: 0.1, parents: [] },
    { id: 'n2', transactionId: 'TXN-100219', x: 0.62, y: 0.08, parents: [] },
    { id: 'n3', transactionId: 'TXN-100234', x: 0.4, y: 0.34, parents: ['n1', 'n2'] },
    { id: 'n4', transactionId: 'TXN-100235', x: 0.14, y: 0.62, parents: ['n3'] },
    { id: 'n5', transactionId: 'TXN-100236', x: 0.42, y: 0.66, parents: ['n3'] },
    { id: 'n6', transactionId: 'TXN-100237', x: 0.72, y: 0.6, parents: ['n3'] },
  ],
  stages: [
    {
      kind: 'CONTEXT_BUILDER',
      title: 'Context Builder',
      actor: 'DETERMINISTIC',
      durationMs: 180,
      summary: 'Assembled a compact evidence package — no raw DB dump reaches Gemma.',
      input: 'CASE-1001 · CUST-001 · trigger TXN-100234',
      output:
        'Evidence package: current_transaction, customer_twin, recent_summary(30d), 4 detected_deviations, kyc_summary(VERIFIED), 1 document (export invoice).',
    },
    {
      kind: 'ORCHESTRATOR',
      title: 'Investigation Orchestrator',
      actor: 'GEMMA',
      durationMs: 940,
      summary: 'Read the package, decided which analyses the case needs.',
      input: 'Compact evidence package + investigation_system prompt.',
      output:
        'Plan: (1) quantify amount + velocity deviation, (2) trace outbound money flow, (3) match export invoice to sender, (4) generate legitimate + suspicious + uncertain scenarios.',
    },
    {
      kind: 'SCENARIO_GENERATOR',
      title: 'Scenario Generator',
      actor: 'GEMMA',
      durationMs: 1120,
      summary: 'Proposed three competing explanations — not a single label.',
      input: 'Investigation plan + detected deviations.',
      output:
        'SCN-1 Transaction Layering (SUSPICIOUS), SCN-2 Legitimate Business Payment (LEGITIMATE), SCN-3 Account Takeover (SUSPICIOUS), each with weighted expected_signals.',
    },
    {
      kind: 'DETERMINISTIC_TOOLS',
      title: 'Deterministic Analysis Tools',
      actor: 'DETERMINISTIC',
      durationMs: 610,
      summary: 'Ran the registered local tools Gemma requested. Gemma invents no numbers.',
      input: 'Tool requests from the orchestrator plan.',
      output: 'All four tools returned; results attached to the case as trusted evidence.',
      toolCalls: [
        {
          tool: 'calculate_amount_deviation',
          args: 'TXN-100234',
          result: 'z=6.4, percentile=99.9, trusted_range=[10K,150K]',
        },
        {
          tool: 'trace_money_flow',
          args: 'TXN-100234, hours=1',
          result: '₹9.5L out to 5 accounts in 40 min; longest hop chain = 1',
        },
        {
          tool: 'get_beneficiary_relationships',
          args: 'CUST-001',
          result: '5 first-seen; known_ratio 0.92→0.41',
        },
        {
          tool: 'verify_invoice_match',
          args: 'TXN-100234, DOC-551',
          result: 'sender_name MATCH; amount 96% match; date within 3d',
        },
      ],
    },
    {
      kind: 'SIMULATOR_SCORER',
      title: 'Simulator & Match Scorer',
      actor: 'DETERMINISTIC',
      durationMs: 420,
      summary: 'Scored each scenario transparently: matched weight ÷ total weight.',
      input: 'Expected signals per scenario + trusted tool evidence.',
      output:
        'Layering 84% · Legitimate Business Payment 71% · Account Takeover 17%. Scoring table is fully auditable.',
    },
    {
      kind: 'EVIDENCE_CRITIC',
      title: 'Evidence Critic',
      actor: 'GEMMA',
      durationMs: 560,
      summary: 'Challenged the strongest hypothesis and surfaced a contradiction.',
      input: 'Top scenarios + supporting/contradicting evidence.',
      output:
        'Contradiction: a valid export invoice weakens pure layering. Account Takeover fails — same device, usual hours, known channel. Uncertainty flagged on beneficiary legitimacy.',
    },
    {
      kind: 'DECISION_EVIDENCE',
      title: 'Decision-Evidence Agent',
      actor: 'GEMMA',
      durationMs: 620,
      summary: 'Found the single fact that separates the two leading stories.',
      input: 'Layering (84%) vs Legitimate (71%) evidence expectations.',
      output:
        'Decision-critical question: “Are the five receiving accounts verified suppliers?” Verified suppliers would drop risk 84→28.',
    },
    {
      kind: 'REPORT_WRITER',
      title: 'Report Writer',
      actor: 'GEMMA',
      durationMs: 370,
      summary: 'Drafted a narrative from verified evidence only — for human sign-off.',
      input: 'Validated structured case evidence.',
      output:
        'Draft compliance narrative generated. Deterministic renderer will insert IDs, scores, timestamps. Awaiting reviewer decision.',
    },
  ],
};

/** CASE-1002 — Meridian Freight (structuring). */
const SANDBOX_1002: Sandbox = {
  runId: 'SBX-1002-c1e9',
  model: 'gemma-3-4b-it',
  runtime: 'llama.cpp · Q4_K_M · localhost',
  boundaryHeld: true,
  seed: 100781,
  totalDurationMs: 4110,
  anomaly: {
    score: 92,
    deviationLevel: 'Severe',
    matters:
      'Six cash deposits of ₹1.9L each — all deliberately below the ₹2L reporting threshold — landed in six cities on the same day with no commercial paperwork.',
    markedRisk:
      'The deposits cluster just under the reporting limit across many locations at once. That threshold-avoidance shape is the classic structuring footprint, so the case is escalated rather than cleared.',
    signals: [
      {
        key: 'threshold',
        label: 'Threshold avoidance',
        metric: 'max / limit',
        value: '₹1.9L < ₹2L',
        contribution: 34,
        fired: true,
        why: 'Every deposit sits at 95% of the ₹2L reporting cap. Six deposits, zero above the line — a near-impossible coincidence for organic activity.',
      },
      {
        key: 'multi_loc',
        label: 'Multi-location clustering',
        metric: 'cities / day',
        value: '6 vs 1',
        contribution: 30,
        fired: true,
        why: 'Normal footprint is a single Chennai branch. Six cities in one day cannot be reached by one operator — points to a coordinated placement.',
      },
      {
        key: 'channel',
        label: 'Channel shift',
        metric: 'digital→cash',
        value: 'Cash / branch',
        contribution: 18,
        fired: true,
        why: 'This twin is digital-first. A sudden all-cash pattern removes the audit trail that digital transfers carry.',
      },
      {
        key: 'no_docs',
        label: 'Missing paperwork',
        metric: 'invoice match',
        value: 'none',
        contribution: 10,
        fired: true,
        why: 'No invoices or sales records back the deposits, so no legitimate commercial story is documented yet.',
      },
    ],
  },
  flow: {
    nodes: [
      { id: 'c1', label: 'Chennai', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
      { id: 'c2', label: 'Coimbatore', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
      { id: 'c3', label: 'Madurai', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
      { id: 'c4', label: 'Trichy', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
      { id: 'cust', label: 'Meridian', kind: 'CUSTOMER' },
      { id: 'c5', label: 'Salem', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
      { id: 'c6', label: 'Erode', kind: 'SOURCE', amount: '₹1.9L', verified: 'UNKNOWN' },
    ],
    edges: [
      { from: 'c1', to: 'cust', amount: '₹1.9L' },
      { from: 'c2', to: 'cust', amount: '₹1.9L' },
      { from: 'c3', to: 'cust', amount: '₹1.9L' },
      { from: 'c4', to: 'cust', amount: '₹1.9L' },
      { from: 'c5', to: 'cust', amount: '₹1.9L' },
      { from: 'c6', to: 'cust', amount: '₹1.9L' },
    ],
  },
  transactions: [
    {
      id: 'TXN-100760',
      label: 'Digital freight invoice',
      amount: '₹76,000',
      timestamp: '2026-07-17 09:40',
      direction: 'IN',
      risky: false,
      riskScore: 8,
      reason: 'Normal digital channel',
      explanation: 'Ordinary digital invoice settlement, in line with the customer’s usual ₹80K average.',
      firedSignals: [],
    },
    {
      id: 'TXN-100775',
      label: 'Chennai cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 09:14',
      direction: 'IN',
      risky: true,
      riskScore: 78,
      reason: 'Below reporting threshold',
      explanation:
        'First of six same-day cash deposits, each sitting at 95% of the ₹2L reporting cap. On its own this looks like a large but plausible cash sale.',
      firedSignals: ['Threshold avoidance', 'Channel shift'],
    },
    {
      id: 'TXN-100777',
      label: 'Coimbatore cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 09:31',
      direction: 'IN',
      risky: true,
      riskScore: 82,
      reason: 'Below reporting threshold',
      explanation: 'Second deposit, different city, same day, same near-threshold amount — the pattern starts to compound.',
      firedSignals: ['Threshold avoidance', 'Multi-location clustering'],
    },
    {
      id: 'TXN-100781',
      label: 'Madurai cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 09:52',
      direction: 'IN',
      risky: true,
      riskScore: 88,
      reason: 'Threshold-avoidance pattern confirmed',
      explanation:
        'The trigger transaction for CASE-1002. Six deposits, six cities, one day, every amount just under the ₹2L limit — statistically implausible without deliberate structuring.',
      firedSignals: ['Threshold avoidance', 'Multi-location clustering', 'Missing paperwork'],
    },
    {
      id: 'TXN-100788',
      label: 'Trichy cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 10:20',
      direction: 'IN',
      risky: true,
      riskScore: 86,
      reason: 'Below reporting threshold',
      explanation: 'Fourth deposit in the same cluster; no supporting sales documentation found for any leg.',
      firedSignals: ['Threshold avoidance', 'Missing paperwork'],
    },
    {
      id: 'TXN-100793',
      label: 'Salem cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 11:05',
      direction: 'IN',
      risky: true,
      riskScore: 85,
      reason: 'Below reporting threshold',
      explanation: 'Fifth deposit — the multi-location clustering signal is now unambiguous.',
      firedSignals: ['Threshold avoidance', 'Multi-location clustering'],
    },
    {
      id: 'TXN-100799',
      label: 'Erode cash deposit',
      amount: '₹1,90,000',
      timestamp: '2026-07-18 11:47',
      direction: 'IN',
      risky: true,
      riskScore: 84,
      reason: 'Below reporting threshold',
      explanation: 'Sixth and final deposit in the cluster, closing a full-day structuring pattern across six branches.',
      firedSignals: ['Threshold avoidance', 'Multi-location clustering'],
    },
  ],
  branches: [
    { id: 'n1', transactionId: 'TXN-100760', x: 0.5, y: 0.06, parents: [] },
    { id: 'n2', transactionId: 'TXN-100775', x: 0.12, y: 0.32, parents: ['n1'] },
    { id: 'n3', transactionId: 'TXN-100777', x: 0.32, y: 0.34, parents: ['n1'] },
    { id: 'n4', transactionId: 'TXN-100781', x: 0.5, y: 0.36, parents: ['n1'] },
    { id: 'n5', transactionId: 'TXN-100788', x: 0.68, y: 0.34, parents: ['n1'] },
    { id: 'n6', transactionId: 'TXN-100793', x: 0.85, y: 0.32, parents: ['n1'] },
    { id: 'n7', transactionId: 'TXN-100799', x: 0.5, y: 0.66, parents: ['n2', 'n3', 'n4', 'n5', 'n6'] },
  ],
  stages: [
    {
      kind: 'CONTEXT_BUILDER',
      title: 'Context Builder',
      actor: 'DETERMINISTIC',
      durationMs: 160,
      summary: 'Bundled six same-day deposits + twin into one package.',
      input: 'CASE-1002 · CUST-014 · 6 trigger deposits',
      output: 'Evidence package with clustered-deposit summary and empty document set.',
    },
    {
      kind: 'ORCHESTRATOR',
      title: 'Investigation Orchestrator',
      actor: 'GEMMA',
      durationMs: 820,
      summary: 'Prioritized threshold + location analysis over amount magnitude.',
      input: 'Evidence package + investigation_system prompt.',
      output: 'Plan: test threshold-avoidance, cluster locations, search for source-of-funds docs.',
    },
    {
      kind: 'SCENARIO_GENERATOR',
      title: 'Scenario Generator',
      actor: 'GEMMA',
      durationMs: 900,
      summary: 'Weighed structuring against an under-documented cash business.',
      input: 'Investigation plan + deviations.',
      output: 'SCN-1 Structuring (SUSPICIOUS), SCN-2 Insufficient Evidence (UNCERTAIN).',
    },
    {
      kind: 'DETERMINISTIC_TOOLS',
      title: 'Deterministic Analysis Tools',
      actor: 'DETERMINISTIC',
      durationMs: 540,
      summary: 'Confirmed the sub-threshold pattern with local computation.',
      input: 'Tool requests from plan.',
      output: 'Both tools returned; no matching documents found.',
      toolCalls: [
        { tool: 'detect_threshold_avoidance', args: 'CASE-1002', result: '6/6 deposits in [1.85L,1.99L]; p(random)<0.1%' },
        { tool: 'cluster_deposit_locations', args: 'CASE-1002', result: '6 distinct cities, span 480km, same day' },
        { tool: 'search_customer_documents', args: 'CUST-014, "sales records"', result: '0 documents indexed' },
      ],
    },
    {
      kind: 'SIMULATOR_SCORER',
      title: 'Simulator & Match Scorer',
      actor: 'DETERMINISTIC',
      durationMs: 360,
      summary: 'Structuring dominated; uncertain scenario stayed open.',
      input: 'Expected signals + evidence.',
      output: 'Structuring 90% · Insufficient Evidence 40%.',
    },
    {
      kind: 'EVIDENCE_CRITIC',
      title: 'Evidence Critic',
      actor: 'GEMMA',
      durationMs: 470,
      summary: 'Noted the only exit: a documented cash source.',
      input: 'Structuring vs uncertain evidence.',
      output: 'No contradiction to structuring exists yet; a verified sales ledger is the only thing that would weaken it.',
    },
    {
      kind: 'DECISION_EVIDENCE',
      title: 'Decision-Evidence Agent',
      actor: 'GEMMA',
      durationMs: 520,
      summary: 'Isolated source-of-funds as the pivotal fact.',
      input: 'Leading scenarios.',
      output: 'Decision-critical: “What is the documented source of the deposited cash?” Matching sales records would drop risk 88→30.',
    },
    {
      kind: 'REPORT_WRITER',
      title: 'Report Writer',
      actor: 'GEMMA',
      durationMs: 340,
      summary: 'Prepared an EDD-oriented draft for escalation.',
      input: 'Validated evidence.',
      output: 'Draft recommends enhanced due diligence; renderer will attach the six deposit IDs.',
    },
  ],
};

/** CASE-1003 — Aarav Menon (legitimate property purchase — the clean case). */
const SANDBOX_1003: Sandbox = {
  runId: 'SBX-1003-9b02',
  model: 'gemma-3-4b-it',
  runtime: 'llama.cpp · Q4_K_M · localhost',
  boundaryHeld: true,
  seed: 101120,
  totalDurationMs: 3260,
  anomaly: {
    score: 63,
    deviationLevel: 'Moderate',
    matters:
      'A ₹8.5L outbound payment is 24× this salaried customer’s ₹35K norm — but it goes to a RERA-registered developer and matches a same-day home-loan disbursement.',
    markedRisk:
      'The amount alone tripped detection, yet the source of funds and beneficiary both check out. Pyxis keeps it in review only to attach the sale agreement — this is what a low-risk deviation looks like.',
    signals: [
      {
        key: 'amount_z',
        label: 'Amount deviation',
        metric: 'z-score',
        value: '4.1σ',
        contribution: 40,
        fired: true,
        why: '₹8.5L is far above the ₹35K median, so detection correctly triggered. Magnitude by itself is never proof of risk.',
      },
      {
        key: 'sof',
        label: 'Source of funds',
        metric: 'match',
        value: 'Loan matched',
        contribution: 0,
        fired: false,
        why: 'A home-loan disbursement of the same amount landed the same day. The money’s origin is fully explained — this signal does NOT fire.',
      },
      {
        key: 'benef',
        label: 'Beneficiary',
        metric: 'registry',
        value: 'RERA-registered',
        contribution: 0,
        fired: false,
        why: 'The developer is on the RERA register. A verified counterparty removes counterparty risk — this signal does NOT fire.',
      },
    ],
  },
  flow: {
    nodes: [
      { id: 'loan', label: 'Home Loan', kind: 'SOURCE', amount: '₹8.5L', verified: 'VERIFIED' },
      { id: 'cust', label: 'A. Menon', kind: 'CUSTOMER' },
      { id: 'dev', label: 'Developer (RERA)', kind: 'BENEFICIARY', amount: '₹8.5L', verified: 'VERIFIED' },
    ],
    edges: [
      { from: 'loan', to: 'cust', amount: '₹8.5L' },
      { from: 'cust', to: 'dev', amount: '₹8.5L' },
    ],
  },
  transactions: [
    {
      id: 'TXN-101090',
      label: 'Monthly salary credit',
      amount: '₹92,000',
      timestamp: '2026-07-01 09:00',
      direction: 'IN',
      risky: false,
      riskScore: 3,
      reason: 'Recurring known credit',
      explanation: 'Standard monthly salary credit from a long-standing employer relationship — no deviation.',
      firedSignals: [],
    },
    {
      id: 'TXN-101105',
      label: 'Utility & card payments',
      amount: '₹31,000',
      timestamp: '2026-07-10 19:22',
      direction: 'OUT',
      risky: false,
      riskScore: 5,
      reason: 'Within trusted range',
      explanation: 'Routine household spending, consistent with the ₹35K typical-amount baseline.',
      firedSignals: [],
    },
    {
      id: 'TXN-101112',
      label: 'Home loan disbursement',
      amount: '₹8,50,000',
      timestamp: '2026-07-17 16:30',
      direction: 'IN',
      risky: false,
      riskScore: 18,
      reason: 'Verified source of funds',
      explanation:
        'Large but fully explained inflow — a home-loan disbursement from a registered lender, same amount as the outbound payment ten minutes later.',
      firedSignals: [],
    },
    {
      id: 'TXN-101120',
      label: 'Property payment to developer',
      amount: '₹8,50,000',
      timestamp: '2026-07-17 16:40',
      direction: 'OUT',
      risky: true,
      riskScore: 63,
      reason: 'Amount deviation (source verified)',
      explanation:
        'The trigger transaction for CASE-1003. ₹8.5L is 24× the customer’s typical spend, which is why detection fired — but the RERA-registered beneficiary and matching loan disbursement keep the current risk low at 34/100.',
      firedSignals: ['Amount deviation'],
    },
  ],
  branches: [
    { id: 'n1', transactionId: 'TXN-101090', x: 0.2, y: 0.08, parents: [] },
    { id: 'n2', transactionId: 'TXN-101105', x: 0.72, y: 0.1, parents: [] },
    { id: 'n3', transactionId: 'TXN-101112', x: 0.3, y: 0.38, parents: ['n1'] },
    { id: 'n4', transactionId: 'TXN-101120', x: 0.55, y: 0.66, parents: ['n2', 'n3'] },
  ],
  stages: [
    {
      kind: 'CONTEXT_BUILDER',
      title: 'Context Builder',
      actor: 'DETERMINISTIC',
      durationMs: 150,
      summary: 'Packaged the single high-value payment with loan context.',
      input: 'CASE-1003 · CUST-233 · trigger TXN-101120',
      output: 'Evidence package with matched home-loan disbursement + developer record.',
    },
    {
      kind: 'ORCHESTRATOR',
      title: 'Investigation Orchestrator',
      actor: 'GEMMA',
      durationMs: 610,
      summary: 'Chose to verify source-of-funds and beneficiary registry first.',
      input: 'Evidence package + prompt.',
      output: 'Plan: match loan to payment, look up developer registration, check for a single vs repeated pattern.',
    },
    {
      kind: 'SCENARIO_GENERATOR',
      title: 'Scenario Generator',
      actor: 'GEMMA',
      durationMs: 720,
      summary: 'One dominant legitimate story, one weak uncertain one.',
      input: 'Plan + deviation.',
      output: 'SCN-1 Property Purchase (LEGITIMATE), SCN-2 Insufficient Evidence (UNCERTAIN).',
    },
    {
      kind: 'DETERMINISTIC_TOOLS',
      title: 'Deterministic Analysis Tools',
      actor: 'DETERMINISTIC',
      durationMs: 430,
      summary: 'Confirmed the loan match and developer registration.',
      input: 'Tool requests.',
      output: 'Both tools returned strong matches.',
      toolCalls: [
        { tool: 'match_source_of_funds', args: 'TXN-101120', result: 'home-loan disbursement, same amount, same day' },
        { tool: 'lookup_beneficiary_registry', args: 'DEV-2201', result: 'RERA registered, active, clean' },
      ],
    },
    {
      kind: 'SIMULATOR_SCORER',
      title: 'Simulator & Match Scorer',
      actor: 'DETERMINISTIC',
      durationMs: 300,
      summary: 'Legitimate scenario clearly led.',
      input: 'Expected signals + evidence.',
      output: 'Property Purchase 86% · Insufficient Evidence 22%.',
    },
    {
      kind: 'EVIDENCE_CRITIC',
      title: 'Evidence Critic',
      actor: 'GEMMA',
      durationMs: 380,
      summary: 'Found no contradiction — risk already low.',
      input: 'Leading scenario evidence.',
      output: 'No unsupported claims. The single remaining gap is the sale agreement document.',
    },
    {
      kind: 'DECISION_EVIDENCE',
      title: 'Decision-Evidence Agent',
      actor: 'GEMMA',
      durationMs: 380,
      summary: 'Identified the one attachment that closes the case.',
      input: 'Leading scenario.',
      output: 'Decision-critical: “Does the sale agreement match amount and developer?” Attaching it drops risk 34→12.',
    },
    {
      kind: 'REPORT_WRITER',
      title: 'Report Writer',
      actor: 'GEMMA',
      durationMs: 290,
      summary: 'Drafted a clear-with-evidence narrative.',
      input: 'Validated evidence.',
      output: 'Draft recommends clearing once the agreement is attached; twin may then learn the new baseline gradually.',
    },
  ],
};

/** CASE-1004 — Lotus Exports (high-risk jurisdiction, genuinely uncertain). */
const SANDBOX_1004: Sandbox = {
  runId: 'SBX-1004-4d77',
  model: 'gemma-3-4b-it',
  runtime: 'llama.cpp · Q4_K_M · localhost',
  boundaryHeld: true,
  seed: 101455,
  totalDurationMs: 3740,
  anomaly: {
    score: 71,
    deviationLevel: 'Moderate',
    matters:
      'A ₹4.2L transfer — 3.5× the ₹1.2L norm — is this exporter’s first-ever payment into a high-risk jurisdiction, to a brand-new beneficiary.',
    markedRisk:
      'A purchase order supports genuine expansion, but the destination and new counterparty raise exposure. The two stories are close, so Pyxis holds the case until the counterparty is screened.',
    signals: [
      {
        key: 'geo',
        label: 'High-risk geography',
        metric: 'risk tier',
        value: 'Tier-3',
        contribution: 30,
        fired: true,
        why: 'First transfer into a flagged jurisdiction. Corridor risk applies regardless of amount.',
      },
      {
        key: 'benef',
        label: 'New beneficiary',
        metric: 'first-seen',
        value: 'yes',
        contribution: 22,
        fired: true,
        why: 'The overseas counterparty has no prior relationship and no completed due diligence.',
      },
      {
        key: 'amount_z',
        label: 'Amount deviation',
        metric: 'z-score',
        value: '2.6σ',
        contribution: 12,
        fired: true,
        why: '₹4.2L is above P95 (₹3.1L) but consistent with a growing export business — a moderate, not extreme, signal.',
      },
      {
        key: 'po',
        label: 'Purchase order',
        metric: 'document',
        value: 'present',
        contribution: 0,
        fired: false,
        why: 'A matching purchase order is on file, supporting the legitimate-expansion story — this signal does NOT fire.',
      },
    ],
  },
  flow: {
    nodes: [
      { id: 'cust', label: 'Lotus Exports', kind: 'CUSTOMER' },
      { id: 'cp', label: 'Overseas CP', kind: 'BENEFICIARY', amount: '₹4.2L', verified: 'UNKNOWN' },
    ],
    edges: [{ from: 'cust', to: 'cp', amount: '₹4.2L' }],
  },
  transactions: [
    {
      id: 'TXN-101430',
      label: 'Domestic export receipt',
      amount: '₹1,10,000',
      timestamp: '2026-07-14 10:15',
      direction: 'IN',
      risky: false,
      riskScore: 9,
      reason: 'Within trusted range',
      explanation: 'Ordinary receipt from an established India-based buyer, in line with the twin.',
      firedSignals: [],
    },
    {
      id: 'TXN-101442',
      label: 'UAE buyer settlement',
      amount: '₹1,35,000',
      timestamp: '2026-07-16 08:30',
      direction: 'IN',
      risky: false,
      riskScore: 14,
      reason: 'Known corridor',
      explanation: 'UAE is one of this exporter’s established geographies, so this credit adds minimal risk.',
      firedSignals: [],
    },
    {
      id: 'TXN-101455',
      label: 'Transfer to overseas counterparty',
      amount: '₹4,20,000',
      timestamp: '2026-07-17 11:05',
      direction: 'OUT',
      risky: true,
      riskScore: 71,
      reason: 'High-risk jurisdiction, new beneficiary',
      explanation:
        'The trigger transaction for CASE-1004. First-ever payment into a flagged jurisdiction to a brand-new, unscreened beneficiary — a matching purchase order keeps this genuinely uncertain rather than clearly suspicious.',
      firedSignals: ['High-risk geography', 'New beneficiary', 'Amount deviation'],
    },
  ],
  branches: [
    { id: 'n1', transactionId: 'TXN-101430', x: 0.22, y: 0.1, parents: [] },
    { id: 'n2', transactionId: 'TXN-101442', x: 0.7, y: 0.12, parents: [] },
    { id: 'n3', transactionId: 'TXN-101455', x: 0.48, y: 0.5, parents: ['n1', 'n2'] },
  ],
  stages: [
    {
      kind: 'CONTEXT_BUILDER',
      title: 'Context Builder',
      actor: 'DETERMINISTIC',
      durationMs: 160,
      summary: 'Bundled the transfer with the export twin and the purchase order.',
      input: 'CASE-1004 · CUST-089 · trigger TXN-101455',
      output: 'Evidence package with corridor-risk flag and one purchase-order document.',
    },
    {
      kind: 'ORCHESTRATOR',
      title: 'Investigation Orchestrator',
      actor: 'GEMMA',
      durationMs: 700,
      summary: 'Balanced expansion vs. counterparty exposure.',
      input: 'Evidence package + prompt.',
      output: 'Plan: screen counterparty, weigh purchase order, assess corridor risk.',
    },
    {
      kind: 'SCENARIO_GENERATOR',
      title: 'Scenario Generator',
      actor: 'GEMMA',
      durationMs: 820,
      summary: 'Produced two near-balanced competing stories.',
      input: 'Plan + deviations.',
      output: 'SCN-1 Business Expansion (LEGITIMATE), SCN-2 High-Risk Counterparty (SUSPICIOUS).',
    },
    {
      kind: 'DETERMINISTIC_TOOLS',
      title: 'Deterministic Analysis Tools',
      actor: 'DETERMINISTIC',
      durationMs: 560,
      summary: 'Screening returned inconclusive — the crux of the case.',
      input: 'Tool requests.',
      output: 'Purchase order matched; counterparty screening incomplete.',
      toolCalls: [
        { tool: 'verify_invoice_match', args: 'TXN-101455, DOC-903', result: 'purchase order matches amount + goods' },
        { tool: 'screen_counterparty', args: 'CP-77', result: 'no adverse hit, but registration UNVERIFIED' },
      ],
    },
    {
      kind: 'SIMULATOR_SCORER',
      title: 'Simulator & Match Scorer',
      actor: 'DETERMINISTIC',
      durationMs: 340,
      summary: 'Scenarios stayed close — genuine uncertainty.',
      input: 'Expected signals + evidence.',
      output: 'Business Expansion 64% · High-Risk Counterparty 52%.',
    },
    {
      kind: 'EVIDENCE_CRITIC',
      title: 'Evidence Critic',
      actor: 'GEMMA',
      durationMs: 460,
      summary: 'Warned that the purchase order alone cannot clear corridor risk.',
      input: 'Both scenarios’ evidence.',
      output: 'A valid PO supports legitimacy but does not verify the counterparty is a real registered entity.',
    },
    {
      kind: 'DECISION_EVIDENCE',
      title: 'Decision-Evidence Agent',
      actor: 'GEMMA',
      durationMs: 500,
      summary: 'Pinned counterparty legitimacy as decisive.',
      input: 'Two near-tied scenarios.',
      output: 'Decision-critical: “Is the overseas counterparty a legitimate registered entity?” Passing screening drops risk 58→20.',
    },
    {
      kind: 'REPORT_WRITER',
      title: 'Report Writer',
      actor: 'GEMMA',
      durationMs: 300,
      summary: 'Drafted a hold-pending-screening narrative.',
      input: 'Validated evidence.',
      output: 'Draft recommends enhanced monitoring on the new corridor until registration documents are verified.',
    },
  ],
};

export const SANDBOXES: Record<string, Sandbox> = {
  'CASE-1001': SANDBOX_1001,
  'CASE-1002': SANDBOX_1002,
  'CASE-1003': SANDBOX_1003,
  'CASE-1004': SANDBOX_1004,
};
